//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import_Eqp.EqpService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpInsertUpdateRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpInsertUpdateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Import_Eqp.EqpService.EqpInsertUpdateRequestHeader headerFieldField;
        
        private Import_Eqp.EqpService.EqpInsertUpdateRequestItem itemFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Import_Eqp.EqpService.EqpInsertUpdateRequestHeader headerField {
            get {
                return this.headerFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.headerFieldField, value) != true)) {
                    this.headerFieldField = value;
                    this.RaisePropertyChanged("headerField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Import_Eqp.EqpService.EqpInsertUpdateRequestItem itemField {
            get {
                return this.itemFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.itemFieldField, value) != true)) {
                    this.itemFieldField = value;
                    this.RaisePropertyChanged("itemField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpInsertUpdateRequestHeader", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpInsertUpdateRequestHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long fileIdFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long fileIdField {
            get {
                return this.fileIdFieldField;
            }
            set {
                if ((this.fileIdFieldField.Equals(value) != true)) {
                    this.fileIdFieldField = value;
                    this.RaisePropertyChanged("fileIdField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpInsertUpdateRequestItem", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpInsertUpdateRequestItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkCommentFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkContentFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkDateFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkDocDateFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkDocFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkNextDateFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkPlaceFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string checkTypeFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string executerFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extensionIdFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string factoryFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string inAccrScopeFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string intervalLenFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string intervalTypeFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invNumFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemNameFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemNoteFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kindFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string legalBasisFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mnfDateFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mnfFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mnfNumFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purposeFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startUpFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subdivisionFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeNameFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkCommentField {
            get {
                return this.checkCommentFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkCommentFieldField, value) != true)) {
                    this.checkCommentFieldField = value;
                    this.RaisePropertyChanged("checkCommentField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkContentField {
            get {
                return this.checkContentFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkContentFieldField, value) != true)) {
                    this.checkContentFieldField = value;
                    this.RaisePropertyChanged("checkContentField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkDateField {
            get {
                return this.checkDateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkDateFieldField, value) != true)) {
                    this.checkDateFieldField = value;
                    this.RaisePropertyChanged("checkDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkDocDateField {
            get {
                return this.checkDocDateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkDocDateFieldField, value) != true)) {
                    this.checkDocDateFieldField = value;
                    this.RaisePropertyChanged("checkDocDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkDocField {
            get {
                return this.checkDocFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkDocFieldField, value) != true)) {
                    this.checkDocFieldField = value;
                    this.RaisePropertyChanged("checkDocField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkNextDateField {
            get {
                return this.checkNextDateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkNextDateFieldField, value) != true)) {
                    this.checkNextDateFieldField = value;
                    this.RaisePropertyChanged("checkNextDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkPlaceField {
            get {
                return this.checkPlaceFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkPlaceFieldField, value) != true)) {
                    this.checkPlaceFieldField = value;
                    this.RaisePropertyChanged("checkPlaceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string checkTypeField {
            get {
                return this.checkTypeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.checkTypeFieldField, value) != true)) {
                    this.checkTypeFieldField = value;
                    this.RaisePropertyChanged("checkTypeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string executerField {
            get {
                return this.executerFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.executerFieldField, value) != true)) {
                    this.executerFieldField = value;
                    this.RaisePropertyChanged("executerField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extensionIdField {
            get {
                return this.extensionIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.extensionIdFieldField, value) != true)) {
                    this.extensionIdFieldField = value;
                    this.RaisePropertyChanged("extensionIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string factoryField {
            get {
                return this.factoryFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.factoryFieldField, value) != true)) {
                    this.factoryFieldField = value;
                    this.RaisePropertyChanged("factoryField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inAccrScopeField {
            get {
                return this.inAccrScopeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.inAccrScopeFieldField, value) != true)) {
                    this.inAccrScopeFieldField = value;
                    this.RaisePropertyChanged("inAccrScopeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string intervalLenField {
            get {
                return this.intervalLenFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.intervalLenFieldField, value) != true)) {
                    this.intervalLenFieldField = value;
                    this.RaisePropertyChanged("intervalLenField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string intervalTypeField {
            get {
                return this.intervalTypeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.intervalTypeFieldField, value) != true)) {
                    this.intervalTypeFieldField = value;
                    this.RaisePropertyChanged("intervalTypeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invNumField {
            get {
                return this.invNumFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.invNumFieldField, value) != true)) {
                    this.invNumFieldField = value;
                    this.RaisePropertyChanged("invNumField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemNameField {
            get {
                return this.itemNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.itemNameFieldField, value) != true)) {
                    this.itemNameFieldField = value;
                    this.RaisePropertyChanged("itemNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemNoteField {
            get {
                return this.itemNoteFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.itemNoteFieldField, value) != true)) {
                    this.itemNoteFieldField = value;
                    this.RaisePropertyChanged("itemNoteField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kindField {
            get {
                return this.kindFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.kindFieldField, value) != true)) {
                    this.kindFieldField = value;
                    this.RaisePropertyChanged("kindField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string legalBasisField {
            get {
                return this.legalBasisFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.legalBasisFieldField, value) != true)) {
                    this.legalBasisFieldField = value;
                    this.RaisePropertyChanged("legalBasisField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationField {
            get {
                return this.locationFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.locationFieldField, value) != true)) {
                    this.locationFieldField = value;
                    this.RaisePropertyChanged("locationField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mnfDateField {
            get {
                return this.mnfDateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.mnfDateFieldField, value) != true)) {
                    this.mnfDateFieldField = value;
                    this.RaisePropertyChanged("mnfDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mnfField {
            get {
                return this.mnfFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.mnfFieldField, value) != true)) {
                    this.mnfFieldField = value;
                    this.RaisePropertyChanged("mnfField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mnfNumField {
            get {
                return this.mnfNumFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.mnfNumFieldField, value) != true)) {
                    this.mnfNumFieldField = value;
                    this.RaisePropertyChanged("mnfNumField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purposeField {
            get {
                return this.purposeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.purposeFieldField, value) != true)) {
                    this.purposeFieldField = value;
                    this.RaisePropertyChanged("purposeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startUpField {
            get {
                return this.startUpFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.startUpFieldField, value) != true)) {
                    this.startUpFieldField = value;
                    this.RaisePropertyChanged("startUpField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateField {
            get {
                return this.stateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.stateFieldField, value) != true)) {
                    this.stateFieldField = value;
                    this.RaisePropertyChanged("stateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subdivisionField {
            get {
                return this.subdivisionFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.subdivisionFieldField, value) != true)) {
                    this.subdivisionFieldField = value;
                    this.RaisePropertyChanged("subdivisionField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeNameField {
            get {
                return this.typeNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.typeNameFieldField, value) != true)) {
                    this.typeNameFieldField = value;
                    this.RaisePropertyChanged("typeNameField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpGSOAnswer", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpGSOAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Import_Eqp.EqpService.EqpGSOAnswerHeader headerFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Import_Eqp.EqpService.EqpGSOAnswerHeader headerField {
            get {
                return this.headerFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.headerFieldField, value) != true)) {
                    this.headerFieldField = value;
                    this.RaisePropertyChanged("headerField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpGSOAnswerHeader", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpGSOAnswerHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int errCodeFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errMsgFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long fileIdFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int errCodeField {
            get {
                return this.errCodeFieldField;
            }
            set {
                if ((this.errCodeFieldField.Equals(value) != true)) {
                    this.errCodeFieldField = value;
                    this.RaisePropertyChanged("errCodeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errMsgField {
            get {
                return this.errMsgFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.errMsgFieldField, value) != true)) {
                    this.errMsgFieldField = value;
                    this.RaisePropertyChanged("errMsgField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long fileIdField {
            get {
                return this.fileIdFieldField;
            }
            set {
                if ((this.fileIdFieldField.Equals(value) != true)) {
                    this.fileIdFieldField = value;
                    this.RaisePropertyChanged("fileIdField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpDeleteRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpDeleteRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Import_Eqp.EqpService.EqpDeleteRequestHeader headerFieldField;
        
        private Import_Eqp.EqpService.EqpDeleteRequestItem itemFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Import_Eqp.EqpService.EqpDeleteRequestHeader headerField {
            get {
                return this.headerFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.headerFieldField, value) != true)) {
                    this.headerFieldField = value;
                    this.RaisePropertyChanged("headerField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Import_Eqp.EqpService.EqpDeleteRequestItem itemField {
            get {
                return this.itemFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.itemFieldField, value) != true)) {
                    this.itemFieldField = value;
                    this.RaisePropertyChanged("itemField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpDeleteRequestHeader", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpDeleteRequestHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long fileIdFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long fileIdField {
            get {
                return this.fileIdFieldField;
            }
            set {
                if ((this.fileIdFieldField.Equals(value) != true)) {
                    this.fileIdFieldField = value;
                    this.RaisePropertyChanged("fileIdField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EqpDeleteRequestItem", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EqpDeleteRequestItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extensionIdFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string factoryFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invNumFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subdivisionFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extensionIdField {
            get {
                return this.extensionIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.extensionIdFieldField, value) != true)) {
                    this.extensionIdFieldField = value;
                    this.RaisePropertyChanged("extensionIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string factoryField {
            get {
                return this.factoryFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.factoryFieldField, value) != true)) {
                    this.factoryFieldField = value;
                    this.RaisePropertyChanged("factoryField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invNumField {
            get {
                return this.invNumFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.invNumFieldField, value) != true)) {
                    this.invNumFieldField = value;
                    this.RaisePropertyChanged("invNumField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subdivisionField {
            get {
                return this.subdivisionFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.subdivisionFieldField, value) != true)) {
                    this.subdivisionFieldField = value;
                    this.RaisePropertyChanged("subdivisionField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EqpService.IEqpIntegrationService")]
    public interface IEqpIntegrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEqpIntegrationService/InsUpd", ReplyAction="http://tempuri.org/IEqpIntegrationService/InsUpdResponse")]
        Import_Eqp.EqpService.EqpGSOAnswer InsUpd(Import_Eqp.EqpService.EqpInsertUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEqpIntegrationService/InsUpd", ReplyAction="http://tempuri.org/IEqpIntegrationService/InsUpdResponse")]
        System.Threading.Tasks.Task<Import_Eqp.EqpService.EqpGSOAnswer> InsUpdAsync(Import_Eqp.EqpService.EqpInsertUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEqpIntegrationService/Delete", ReplyAction="http://tempuri.org/IEqpIntegrationService/DeleteResponse")]
        Import_Eqp.EqpService.EqpGSOAnswer Delete(Import_Eqp.EqpService.EqpDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEqpIntegrationService/Delete", ReplyAction="http://tempuri.org/IEqpIntegrationService/DeleteResponse")]
        System.Threading.Tasks.Task<Import_Eqp.EqpService.EqpGSOAnswer> DeleteAsync(Import_Eqp.EqpService.EqpDeleteRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEqpIntegrationServiceChannel : Import_Eqp.EqpService.IEqpIntegrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EqpIntegrationServiceClient : System.ServiceModel.ClientBase<Import_Eqp.EqpService.IEqpIntegrationService>, Import_Eqp.EqpService.IEqpIntegrationService {
        
        public EqpIntegrationServiceClient() {
        }
        
        public EqpIntegrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EqpIntegrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EqpIntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EqpIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Import_Eqp.EqpService.EqpGSOAnswer InsUpd(Import_Eqp.EqpService.EqpInsertUpdateRequest request) {
            return base.Channel.InsUpd(request);
        }
        
        public System.Threading.Tasks.Task<Import_Eqp.EqpService.EqpGSOAnswer> InsUpdAsync(Import_Eqp.EqpService.EqpInsertUpdateRequest request) {
            return base.Channel.InsUpdAsync(request);
        }
        
        public Import_Eqp.EqpService.EqpGSOAnswer Delete(Import_Eqp.EqpService.EqpDeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public System.Threading.Tasks.Task<Import_Eqp.EqpService.EqpGSOAnswer> DeleteAsync(Import_Eqp.EqpService.EqpDeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
    }
}
